import { Sidebar } from "@/components/Sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {/* TODO: Passar valor da grid para tema */}
        <div className="grid min-h-dvh grid-cols-[minmax(18rem,_20rem)_1fr]">
          <Sidebar />

          <main className="px-4 pt-24 pb-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
